kbbotapp/urls.py
from django.urls import path

from .views import Home, Chat
from .views import ConfigHome, SettingsHome, SettingsUpdate,SettingsReset
from .views import IndexHome, IndexCreateJSON, IndexUpload, IndexCreate
from .views import DocumentList, DocumentAdd, DocumentDetail, DocumentDelete, DocumentUpload

app_name = "kbbotapp"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("chat/", Chat.as_view(), name="chat"),
    path("config/", ConfigHome.as_view(), name="config_home"),
    path("config/settings/", SettingsHome.as_view(), name="config_settings_home"),
    path("config/settings/<pk>/", SettingsUpdate.as_view(), name="config_settings_update"),
    path("config/settings/<pk>/reset/", SettingsReset.as_view(), name="config_settings_reset"),
    path("config/index/", IndexHome.as_view(), name="config_index_home"),
    path("config/index/create/", IndexCreate.as_view(), name="config_index_create"),

    path("config/index/refresh/", IndexCreateJSON.as_view(), name="config_index_refresh"),
    path("config/index/upload/", IndexUpload.as_view(), name="config_index_upload"),
    path("config/documents/", DocumentList.as_view(), name="config_document_list"),
    path("config/documents/upload/", DocumentUpload.as_view(), name="config_document_upload"),
    path("config/document/add/", DocumentAdd.as_view(), name="config_document_add"),
    path("config/document/<pk>/", DocumentDetail.as_view(), name="config_document_detail"),
    path("config/document/<pk>/delete/", DocumentDelete.as_view(), name="config_document_delete"),

]

kbbotdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    #path('', lambda req: redirect('kbbotapp/')),
    path("", include('kbbotapp.urls')),
    path('admin/', admin.site.urls),
]

kbbotapp/forms.py
from django import forms

from .models import Settings

class AskQuestionForm(forms.Form):
    question = forms.CharField(widget=forms.Textarea(attrs={"rows": "5", "placeholder": "Type your query here ..."}),
                               label="")


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Settings
        fields = "__all__"
        fieldsets = (
            "OpenAI", {
                'fields': ("opeanai_api_key", "openai_embedding_model"),
            })
        widgets = {
            "openai_api_key": forms.Textarea(attrs={"cols":50, "rows":1}),
            "azure_cognitive_search_api_key": forms.Textarea(attrs={"cols":50, "rows":1}),
        }

kbbotapp/views.py
import os
import requests
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import render

from django.views.generic.base import TemplateView, RedirectView, View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Document, Page, Settings
from .forms import SettingsForm, AskQuestionForm

from PyPDF2 import PdfReader
import json
import pandas as pd
import openai
import tiktoken
from azure.identity import DefaultAzureCredential
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.indexes import SearchIndexClient, SearchIndexerClient
from azure.search.documents.indexes.models import (
    SearchIndex,
    SearchField,
    SearchFieldDataType,
    SimpleField,
    SearchableField,
    VectorSearch,
    HnswVectorSearchAlgorithmConfiguration,
)
from azure.search.documents.models import Vector
from azure.storage.blob import BlobServiceClient, ContainerClient


# Create your views here.

def read_app_settings()->Settings:
    if Settings.objects.count() == 0:
        Settings.objects.create()
    settings = Settings.objects.first()
    # OPENAI_API_KEY = settings.openai_api_key
    # OPENAI_EMBEDDING_MODEL = settings.openai_embedding_model
    # SEARCH_SERVICE_ENDPOINT = f"https://{settings.azure_cognitive_search_service_name}.search.windows.net"
    # AZURE_CREDENTIAL = AzureKeyCredential(settings.azure_cognitive_search_api_key)
    # INDEX_NAME = settings.azure_cognitive_search_index_name
    # INDEX_STATUS = settings.index_status
    # indexer_name = PS.azure_cognitive_search_indexer_name
    # search_datasource_name = PS.azure_cognitive_search_datasource_name
    return settings

""" -----  HOMEPAGE  ----- """

class Home(ListView):
    model = Document
    template_name = "kbbotapp/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["documents_count"] = Document.objects.count()
        app_settings = read_app_settings()
        context["index_status"] = app_settings.index_status
        context["index_status_text"] = app_settings.get_index_status_display()
        return context
    
""" ----- CHAT ----- """

def openai_api_calculate_cost(prompt_text, completion_text, model="gpt-3.5-turbo"):
    pricing = {
        'gpt-3.5-turbo': {
            'prompt': 0.0015,
            'completion': 0.002,
        },
        'gpt-3.5-turbo-16k': {
            'prompt': 0.003,
            'completion': 0.004,
        },
        'gpt-4': {
            'prompt': 0.03,
            'completion': 0.06,
        },
        'gpt-4-32k': {
            'prompt': 0.06,
            'completion': 0.12,
        },
        'text-embedding-ada-002': {
            'prompt': 0.0001,
            'completion': 0.0001,
        }
    }

    try:
        model_pricing = pricing[model]
    except KeyError:
        raise ValueError("Invalid model specified")
    
    encoding = tiktoken.encoding_for_model(model)
    prompt_tokens = len(encoding.encode(prompt_text))
    completion_tokens = len(encoding.encode(completion_text))
    total_tokens = prompt_tokens + completion_tokens

    prompt_cost = prompt_tokens * model_pricing['prompt'] / 1000
    completion_cost = completion_tokens * model_pricing['completion'] / 1000

    total_cost = prompt_cost + completion_cost
    print(f"\nTokens used:  {prompt_tokens} prompt + {completion_tokens} completion = {total_tokens} tokens")
    print(f"Total cost for {model}: ${total_cost:.4f}\n")

    return {'total_cost': total_cost, 'total_tokens': total_tokens}

class QueryResult():
    sources:list
    answer:str
    cost:float
    tokens:int

    def __init__(self) -> None:
        self.sources = []
        self.answer = ""
        self.tokens = 0
        self.cost = 0

def search_for_answer(query)->QueryResult:
    query_result = QueryResult()
    app_settings = read_app_settings()
    search_client = SearchClient(f"https://{app_settings.azure_cognitive_search_service_name}.search.windows.net"
                                 ,app_settings.azure_cognitive_search_index_name,
                                 AzureKeyCredential(app_settings.azure_cognitive_search_api_key))
    openai.api_key = app_settings.openai_api_key
    embedding = openai.Embedding.create(input=query,
                                        deployment_id=app_settings.openai_embedding_model)["data"][0]["embedding"]
    vector = Vector(value=embedding, k=3, fields="content_vector")
    results = search_client.search(
        search_text="",
        vectors=[vector],
        select=["document_name", "content_text"]
    )
    if results.get_answers():
        print("Answer")
        print(results.get_answers())
    else:
        print("No Answer")
        answer_passage = ""
        for result in results:
            score = result["@search.score"]
            document_name = result['document_name'].replace("_page", " Page ").replace(".txt", "")
            print(f"{result['document_name']}, {score}")
            answer_passage += result["content_text"] + " "
            query_result.sources.append({'name': result['document_name'], 'score': score * 100})

        system_prompt = "You answer the question based on the below knowledge base. If the answer cannot be found in the knowledge base, respont 'Sorry, I could not find the answer in my knowledge base.'. Here is your knowledge base: "
        system_prompt += answer_passage
        chat_messages = [{"role": "system", "content": system_prompt}]
        
        message = query
        chat_messages.append({"role": "user", "content": message},)
        # TODO: calculate prompt_tokens = system_prompt + query

        chat = openai.ChatCompletion.create(model=app_settings.openai_model_name,
                                            messages=chat_messages)
        reply = chat.choices[0].message.content
        print(f"ChatGPT: {reply}")

        # TODO: calculate completion_tokens = reply
        cost_and_tokens = openai_api_calculate_cost(system_prompt + query, reply,
                                                      app_settings.openai_model_name)
        query_result.cost = cost_and_tokens['total_cost']
        query_result.tokens = cost_and_tokens['total_tokens']
        query_result.answer = reply
    return query_result

class Chat(View):
    
    template_name = "kbbotapp/chat.html"
    form_class = AskQuestionForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        # context = super().get_context_data(**kwargs)
        context = {}
        context["documents_count"] = Document.objects.count()
        settings = read_app_settings()
        context["index_status"] = settings.index_status
        context["form"] = form
        context["answer"] = "empty"
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        app_settings = read_app_settings()
        form = self.form_class(data=request.POST)
        context = {}
        context["documents_count"] = Document.objects.count()
        settings = read_app_settings()
        context["index_status"] = settings.index_status
        context["form"] = form
        if form.is_valid():
            query = form.cleaned_data["question"]
            queryresult = search_for_answer(query)
            context["answer"] = queryresult.answer
            context["model"] = app_settings.openai_model_name
            context["tokens"] = queryresult.tokens
            context["cost"] = queryresult.cost
            context["sources"] = queryresult.sources
        return render(request, self.template_name, context)

""" ----- CONFIGURE ----- """

class ConfigHome(TemplateView):
    template_name = "kbbotapp/config_home.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["documents_count"] = Document.objects.count()
        settings = read_app_settings()
        context["setting_pk"] = settings.pk
        context["index_status"] = settings.index_status
        context["index_status_text"] = settings.get_index_status_display()
        return context

""" ----- CONFIGURE / SETTINGS ----- """

class SettingsHome(TemplateView):
    template_name = "kbbotapp/config_settings_home.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        app_settings = read_app_settings()
        context["settings"] = app_settings
        fields = []
        for f in Settings._meta.get_fields():
            if f.name != "id":
                fieldname = f.verbose_name
                if f.name == "index_status":
                    fieldvalue = app_settings.get_index_status_display()
                else:
                    fieldvalue = getattr(app_settings,f.name)
                fields.append({'name': fieldname, 'value': fieldvalue})
        context["setting_fields"] = fields
        return context

""" ----- CONFIGURE / SETTINGS / UPDATE ----- """

class SettingsUpdate(UpdateView):
    model = Settings
    template_name = "kbbotapp/config_settings_update.html"
    form_class = SettingsForm
    success_url = reverse_lazy("kbbotapp:config_settings_home")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        settings = read_app_settings()
        context["setting_pk"] = settings.pk
        return context

""" ----- CONFIGURE / SETTINGS / RESET ----- """

class SettingsReset(RedirectView):
    url = "../../"

    def get_redirect_url(self, *args, **kwargs):
        Settings.objects.all().delete()

kbbotapp/templates/kbbotapp/chat.html
<!DOCTYPE html>
{% extends "kbbotapp/layout.html" %}
{% load django_bootstrap5 %}
{% block head %}
    <script>
        function hideAnswer() {
            showSpinner();
            document.getElementById("answer").style.display = "none";
        }
    </script>
{% endblock %}
{% block title %}
Chat
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:chat' %}">Chat</a>
{% endblock %}
{% block page_title %}
    Chat
{% endblock %}
{% block content %}
    {% if documents_count == 0 %}
        <p>There are no documents in the knowledge base. 
        <a class="btn btn-sm btn-outline-primary" href="{% url 'kbbotapp:config_document_list' %}">Configure Documents</a>
        </p>
    {% else %}
        <form action="" method="post" onsubmit="hideAnswer()">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">
                <span id="spinner-button" class="spinner-border spinner-border-sm" style="display: none;"></span>
                Submit Question
            </button>
        </form>        
    {% endif %}
        <p></p>
    {% if answer != "empty" %}
        <div id="answer" class="card">
            <div class="card-header">
                The Answer
            </div>
            <div class="card-body">
                <div class="text-success">{{ answer }}</div>
            </div>
            <div class="card-footer">
                <div>
                    <small class="text-muted"> used {{ model}} for {{ tokens }} tokens / {{ cost|floatformat:4 }} USD </small>
                </div>
                {% for s in sources%}   
                    <div>
                        <small class="text-muted">{{ s.score|floatformat:2 }}% {{ s.name }}</small>
                    </div>
                {% endfor%}
            </div>
        </div>
    {% endif %}
{% endblock %}

kbbotapp/templates/kbbotapp/config_document_add.html
{% extends "kbbotapp/layout.html" %}
{% load django_bootstrap5 %}
{% block title %}
    Add Document
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}" class="crumb-item">Configure</a> >
    <a href="{% url 'kbbotapp:config_document_list' %}" class="crumb-item">Documents</a> >
    <a href="{% url 'kbbotapp:config_document_add' %}" class="crumb-item">Add Document</a>
{% endblock %}
{% block page_title %}
    Add Document
{% endblock %}
{% block content %}
    <form method="POST" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        <!-- Using the formset -->
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary" onclick="showSpinner();">
            <span id="spinner-button" class="spinner-border spinner-border-sm" style="display: none;"></span>
            Upload
        </button>
        <a href="{% url 'kbbotapp:config_document_list'%}" class="btn btn-outline-secondary">Cancel</a>
    </form>
{% endblock %}

kbbotapp/templates/kbbotapp/config_document_confirm_delete.html
{% extends "kbbotapp/layout.html" %}
{% block title %}
Delete Document
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:config_home' %}">Configure</a> >
    <a href="{% url 'kbbotapp:config_document_list' %}">Documents</a> >
    <a href="{% url 'kbbotapp:config_document_detail' pk=document.pk%}">Delete Document</a>
{% endblock %}
{% block page_title %}
    Delete Document
{% endblock %}
{% block content %}
    <form method="POST" class="form">
        {% csrf_token %}
        <p>Are you sure that you want to delete the document: <mark>{{document}}</mark>?</p>
        <button type="submit" class="btn btn-primary" onclick="showSpinner();">
            <span id="spinner-button" class="spinner-border spinner-border-sm" style="display: none;"></span>
            Delete
        </button>
        <a href="{% url 'kbbotapp:config_document_list'%}" class="btn btn-outline-secondary">Cancel</a>
    </form>
{% endblock %}

kbbotapp/templates/kbbotapp/config_document_detail.html
{% extends "kbbotapp/layout.html" %}
{% block title %}
Document
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}">Configure</a> >
    <a href="{% url 'kbbotapp:config_document_list' %}">Documents</a> >
    <a href="{% url 'kbbotapp:config_document_detail' pk=document.pk%}">View Document</a>
{% endblock %}
{% block page_title %}
    Document
{% endblock %}
{% block actions %}
    <a class="btn btn-sm btn-outline-primary" href="{% url 'kbbotapp:config_document_delete' pk=document.pk %}">
        Delete Document
    </a>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-2">Document Id:</div><div class="col-10">{{ document.pk }}</div>
    </div>
    <div class="row">
        <div class="col-2">Document Name:</div><div class="col-10">{{ document.name }}</div>
    </div>
    <div class="row">
        <div class="col-2">File name:</div><div class="col-10">{{ document.sourcefile.name }}</div>
    </div>
    <p>Pages:</p>
    <div class="row">
        <div class="row">
            <div class="col-1"><strong>No</strong></div>
            <div class="col-7"><strong>Content</strong></div>
            <div class="col-4"><strong>Vector</strong></div>
        </div>
        {% for p in pages %}
        <div class="row">
            <div class="col-1">{{ p.no }}</div>
            <div class="col-7">{{ p.content_text|truncatechars:350 }}</div>
            <div class="col-4">{{ p.content_vector|truncatechars:150 }}</div>
        </div>
        {% endfor %}    
    </div>
{% endblock %}

kbbotapp/templates/kbbotapp/config_document_list.html
{% extends "kbbotapp/layout.html" %}
{% block title %}
Documents
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}">Configure</a> >
    <a href="{% url 'kbbotapp:config_document_list' %}">Documents</a>
{% endblock %}
{% block page_title %}
    Documents
{% endblock %}
{% block actions %}
    <a class="btn btn-sm btn-outline-primary" href="{% url 'kbbotapp:config_document_add' %}">Add New Document</a>
    {% if documents_count > 0 %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'kbbotapp:config_document_upload'%}" onclick="showSpinner()">Upload Pages to Container</a>
    {% endif %}
{% endblock %}
{% block content %}
    <!-- Iterate over object_list -->
    {% for document in document_list %} 
    <!-- Display Objects -->
    <div class="row" style="padding: 3px;">
        <div class="col-3">
            <a href="{% url 'kbbotapp:config_document_detail' pk=document.pk %}">{{ document.name }}</a> 
        </div>
        <div class="col-7">
            {{ document.file_name }}
        </div>
        <div class="col-1">
            {{ document.pages.count }} pages
        </div>
        <div class="col-1">
            <a href="{% url 'kbbotapp:config_document_delete' pk=document.pk %}" class="btn btn-sm btn-outline-primary">Delete</a> 
        </div>
    </div>
    <!-- If object_list is empty  -->
    {% empty %} 
    <li>No objects yet.</li> 
    {% endfor %} 
{% endblock %}

kbbotapp/templates/kbbotapp/config_home.html
{% extends "kbbotapp/layout.html" %}
{% block title %}
Configure
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}" class="crumb-item">Configure</a>
{% endblock %}
{% block page_title %}
    Configure
{% endblock %}
{% block actions %}
    <a class="btn btn-sm btn-outline-primary" href="{% url 'kbbotapp:config_document_list' %}">Configure Documents</a>
    {% if documents_count > 0%}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'kbbotapp:config_index_home' %}">Configure Index</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'kbbotapp:config_settings_home' %}">Configure Settings</a>
    {% endif %}
{% endblock %}
{% block content %}
<p>
    Number of the documents in the knowledge base: <strong>{{documents_count}}</strong>
</p>
<p>
    The index status is: <strong>{{index_status_text}}</strong>
</p>
{% endblock %}

kbbotapp/templates/kbbotapp/config_index_home.html
{% extends "kbbotapp/layout.html" %}
{% block title %}
Index
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}" class="crumb-item">Configure</a> >
    <a href="{% url 'kbbotapp:config_index_home' %}" class="crumb-item">Index</a>
{% endblock %}
{% block page_title %}
    Index
{% endblock %}
{% block actions %}
    <a class="btn btn-sm btn-outline-primary" href="{% url 'kbbotapp:config_index_create' %}" onclick="showSpinner()">Create Index on Azure</a>
    <a class="btn btn-sm btn-outline-secondary" href="{% url 'kbbotapp:config_index_refresh' %}" onclick="showSpinner()">Create Index JSON</a>
    <a class="btn btn-sm btn-outline-secondary" href="{% url 'kbbotapp:config_index_upload' %}" onclick="showSpinner()">Upload Index JSON</a>
{% endblock %}
{% block content %}
<div id="spinner" class="spinner-border" style="display: none;">faszom</div>
<p>
    Number of the documents in the knowledge base: <strong>{{documents_count}}</strong>
</p>
<p>
    The index status is: <strong>{{index_status_text}}</strong>
</p>
<p>Index Data: </p>
<code> {{ index_data_json|truncatewords:200 }}</code>
{% endblock %}

kbbotapp/templates/kbbotapp/config_settings_home.html
{% extends "kbbotapp/layout.html" %}
{% load django_bootstrap5 %}
{% block title %}
Settings
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}">Configure</a> >
    <a href="{% url 'kbbotapp:config_settings_home' %}">Settings</a>
{% endblock %}
{% block page_title %}
    Settings
{% endblock %}
{% block actions %}
    <a class="btn btn-sm btn-outline-primary" href="{% url 'kbbotapp:config_settings_update' pk=settings.pk %}">Edit Settings</a>
    <a class="btn btn-sm btn-outline-secondary" href="{% url 'kbbotapp:config_settings_reset' pk=settings.pk %}">Reset to Default</a>
{% endblock %}
{% block content %}
    {% for f in setting_fields %}
    <div class="container legend">
        <div class="row">
            <div class="col-4">{{ f.name }}:</div>
            <div class="col-8">{{ f.value }}</div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

kbbotapp/templates/kbbotapp/config_settings_update.html
{% extends "kbbotapp/layout.html" %}
{% load django_bootstrap5 %}
{% block title %}
Settings
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a> >
    <a href="{% url 'kbbotapp:config_home' %}">Configure</a> >
    <a href="{% url 'kbbotapp:config_settings_home' %}">Settings</a> >
    <a href="{% url 'kbbotapp:config_settings_update' pk=setting_pk %}">Edit Settings</a>
{% endblock %}
{% block page_title %}
    Edit Settings
{% endblock %}
{% block content %}
<form method="post">  
    {% csrf_token %}  
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">Save</button>
</form>  
{% endblock %}

kbbotapp/templates/kbbotapp/home.html
<!DOCTYPE html>
{% extends "kbbotapp/layout.html" %}
{% block title %}
Home
{% endblock %}
{% block crumb %}
    <a href="{% url 'kbbotapp:home' %}">Home</a>
{% endblock %}
{% block page_title %}
    Home
{% endblock %}
{% block content %}
<h5>Hello There,</h5>
<p>You can either 
<a href="{% url 'kbbotapp:chat' %}" class="btn btn-sm btn-outline-primary">Chat</a> with me, or 
<a href="{% url 'kbbotapp:config_home' %}" class="btn btn-sm btn-outline-primary">Configure</a> my knowledge base.
<p></p>
<div class="card">
    <div class="card-header text-muted">
        Knowledge Base documents: <strong>{{documents_count}}</strong>
    </div>
    <div class="card-body">
        {% for document in document_list %} 
        <!-- Display Objects -->
        <div class="row" style="padding: 3px;">
            <div class="col-3">
                <strong>{{ document.name }}</strong>
            </div>
            <div class="col-7">
                {{ document.file_name }}
            </div>
            <div class="col-1">
                {{ document.pages.count }} pages
            </div>
        </div>
        <!-- If object_list is empty  -->
        {% empty %} 
        <li>No documents yet.</li> 
        {% endfor %}         
    </div>
    <div class="card-footer text-muted">
        Index status: <strong>{{index_status_text}}</strong>
    </div>
</div>

{% endblock %}

kbbotapp/templates/kbbotapp/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    <style>
        .container,
        .container-fluid,
        .container-lg,
        .container-md,
        .container-sm,
        .container-xl,
        .container-xxl {
            margin-top: 5px;
            margin-right: 5px;
            margin-left: 5px;
        }
    </style>
    {% bootstrap_javascript %}
    {% block head %}{% endblock %}
    <!--{% load static %}-->
    <!--link rel="stylesheet" type="text/css" href="{% static 'kbbotapp/site.css' %}"/-->
    <script>
        function showSpinner() {
            document.getElementById("spinner").style.display = "inline-block";
            document.getElementById("spinner-button").style.display = "inline-block";
        }
    </script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'kbbotapp:home' %}">KB Bot Admin</a>
<!--                 <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kbbotapp:home' %}">Home</a>
                    </li>
                </ul>
 -->            </div>
        </nav>
        <div class="crumb">
            Navigation: {% block crumb%}{% endblock %}
        </div>
        <p></p>
        {% bootstrap_messages %}
        <p></p>        
        <div class="card shadow">
            <div class="card-body">
                <h2>{% block page_title %}{% endblock %}</h2>
                <div>
                    {% block actions %}{% endblock %}
                </div>
                <p></p>
                <div id="spinner" class="flex justify-content-left" style="display:none">
                    <div class="spinner-border text-warning" role="status"></div>
                    <span class="text-white">..</span>
                    <span class="text-warning" style="display: inline;"> Working, please wait ...</span>
                </div>
            </div>
        </div>
        <p></p>   
        <div class="card shadow"> 
            <div class="card-body">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <p></p>
        <footer>
            <div class="card shadow">
                <div class="card-body">
                    &copy; KB-Bot 2023
                </div>
            </div>
        </footer>
</div>
</body>
</html>